// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBio1_n-ueToTwzls3OW22N2RWj7qYRhQ',
    appId: '1:1020294372115:web:2f58912c9e87ad9d4918e6',
    messagingSenderId: '1020294372115',
    projectId: 'quick-read-app-2024',
    authDomain: 'quick-read-app-2024.firebaseapp.com',
    storageBucket: 'quick-read-app-2024.appspot.com',
    measurementId: 'G-GP2EVC5D95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvX7PpcO6Zf_KXdmFR8ioYK4qkmZGbODo',
    appId: '1:1020294372115:android:dd5b6f9f3f4752994918e6',
    messagingSenderId: '1020294372115',
    projectId: 'quick-read-app-2024',
    storageBucket: 'quick-read-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNaqfeix6XK1zau6wU9UGWku85ixjSwi4',
    appId: '1:1020294372115:ios:4601597b9d612da74918e6',
    messagingSenderId: '1020294372115',
    projectId: 'quick-read-app-2024',
    storageBucket: 'quick-read-app-2024.appspot.com',
    iosBundleId: 'com.example.quickRead',
  );
}
